BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "firmcraft-bsp"
BBFILE_PATTERN_firmcraft-bsp := "^${LAYERDIR}/"
LAYERVERSION_firmcraft-bsp = "1"
LAYERSERIES_COMPAT_firmcraft-bsp = "scarthgap"